namespace M2Server
{
  partial class TfrmHumanInfo
    {
        public System.Windows.Forms.TabControl PageControl1;
        public System.Windows.Forms.TabPage TabSheet1;
        public System.Windows.Forms.GroupBox GroupBox1;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.TextBox EditName;
        public System.Windows.Forms.TextBox EditMap;
        public System.Windows.Forms.TextBox EditXY;
        public System.Windows.Forms.TextBox EditAccount;
        public System.Windows.Forms.TextBox EditIPaddr;
        public System.Windows.Forms.TextBox EditLogonTime;
        public System.Windows.Forms.TextBox EditLogonLong;
        public System.Windows.Forms.GroupBox GroupBox11;
        public System.Windows.Forms.Label Label20;
        public System.Windows.Forms.TextBox EditSayMsg;
        public System.Windows.Forms.TabPage TabSheet2;
        public System.Windows.Forms.GroupBox GroupBox2;
        public System.Windows.Forms.Label Label12;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.Label Label21;
        public System.Windows.Forms.Label Label32;
        public System.Windows.Forms.Label Label34;
        public System.Windows.Forms.NumericUpDown EditLevel;
        public System.Windows.Forms.NumericUpDown EditGold;
        public System.Windows.Forms.NumericUpDown EditPKPoint;
        public System.Windows.Forms.NumericUpDown EditExp;
        public System.Windows.Forms.NumericUpDown EditMaxExp;
        public System.Windows.Forms.NumericUpDown EditNGLevel;
        public System.Windows.Forms.NumericUpDown EditExpSkill69;
        public System.Windows.Forms.GroupBox GroupBox6;
        public System.Windows.Forms.CheckBox CheckBoxGameMaster;
        public System.Windows.Forms.CheckBox CheckBoxSuperMan;
        public System.Windows.Forms.CheckBox CheckBoxObserver;
        public System.Windows.Forms.GroupBox GroupBox9;
        public System.Windows.Forms.Label Label26;
        public System.Windows.Forms.Label Label27;
        public System.Windows.Forms.Label Label28;
        public System.Windows.Forms.Label Label29;
        public System.Windows.Forms.Label Label19;
        public System.Windows.Forms.Label Label25;
        public System.Windows.Forms.Label Label30;
        public System.Windows.Forms.NumericUpDown EditGameGold;
        public System.Windows.Forms.NumericUpDown EditGamePoint;
        public System.Windows.Forms.NumericUpDown EditCreditPoint;
        public System.Windows.Forms.NumericUpDown EditBonusPoint;
        public System.Windows.Forms.NumericUpDown EditEditBonusPointUsed;
        public System.Windows.Forms.NumericUpDown EditGameGird;
        public System.Windows.Forms.NumericUpDown EditGameDiaMond;
        public System.Windows.Forms.TabPage TabSheet3;
        public System.Windows.Forms.GroupBox GroupBox3;
        public System.Windows.Forms.Label Label11;
        public System.Windows.Forms.Label Label13;
        public System.Windows.Forms.Label Label14;
        public System.Windows.Forms.Label Label15;
        public System.Windows.Forms.Label Label16;
        public System.Windows.Forms.Label Label17;
        public System.Windows.Forms.Label Label18;
        public System.Windows.Forms.TextBox EditAC;
        public System.Windows.Forms.TextBox EditMAC;
        public System.Windows.Forms.TextBox EditDC;
        public System.Windows.Forms.TextBox EditMC;
        public System.Windows.Forms.TextBox EditSC;
        public System.Windows.Forms.TextBox EditHP;
        public System.Windows.Forms.TextBox EditMP;
        public System.Windows.Forms.TabPage TabSheet4;
        public System.Windows.Forms.GroupBox GroupBox7;
        public System.Windows.Forms.DataGrid GridUserItem;
        public System.Windows.Forms.TabPage TabSheet5;
        public System.Windows.Forms.GroupBox GroupBox8;
        public System.Windows.Forms.DataGrid GridBagItem;
        public System.Windows.Forms.TabPage TabSheet6;
        public System.Windows.Forms.GroupBox GroupBox10;
        public System.Windows.Forms.DataGrid GridStorageItem;
        public System.Windows.Forms.TabPage TabSheet7;
        public System.Windows.Forms.GroupBox GroupBox12;
        public System.Windows.Forms.Label Label22;
        public System.Windows.Forms.Label Label23;
        public System.Windows.Forms.Label Label24;
        public System.Windows.Forms.TextBox EditHeroName;
        public System.Windows.Forms.TextBox EditHeroMap;
        public System.Windows.Forms.TextBox EditHeroXY;
        public System.Windows.Forms.GroupBox GroupBox13;
        public System.Windows.Forms.Label Label33;
        public System.Windows.Forms.Label Label35;
        public System.Windows.Forms.Label Label36;
        public System.Windows.Forms.Label Label37;
        public System.Windows.Forms.Label Label31;
        public System.Windows.Forms.Label Label38;
        public System.Windows.Forms.Label Label39;
        public System.Windows.Forms.NumericUpDown EditHeroLevel;
        public System.Windows.Forms.NumericUpDown EditHeroPKPoint;
        public System.Windows.Forms.NumericUpDown EditHeroExp;
        public System.Windows.Forms.NumericUpDown EditHeroMaxExp;
        public System.Windows.Forms.NumericUpDown EditHeroLoyal;
        public System.Windows.Forms.NumericUpDown EditHeroNGLevel;
        public System.Windows.Forms.NumericUpDown EditHeroExpSkill69;
        public System.Windows.Forms.TabPage TabSheet8;
        public System.Windows.Forms.GroupBox GroupBox14;
        public System.Windows.Forms.DataGrid GridHeroUserItem;
        public System.Windows.Forms.TabPage TabSheet9;
        public System.Windows.Forms.GroupBox GroupBox15;
        public System.Windows.Forms.DataGrid GridHeroBagItem;
        public System.Windows.Forms.GroupBox GroupBox4;
        public System.Windows.Forms.CheckBox CheckBoxMonitor;
        public System.Windows.Forms.Button ButtonKick;
        public System.Windows.Forms.GroupBox GroupBox5;
        public System.Windows.Forms.TextBox EditHumanStatus;
        public System.Windows.Forms.Button ButtonSave;
        public System.Windows.Forms.Timer Timer;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.PageControl1 = new System.Windows.Forms.TabControl();
            this.TabSheet1 = new System.Windows.Forms.TabPage();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.Label7 = new System.Windows.Forms.Label();
            this.EditName = new System.Windows.Forms.TextBox();
            this.EditMap = new System.Windows.Forms.TextBox();
            this.EditXY = new System.Windows.Forms.TextBox();
            this.EditAccount = new System.Windows.Forms.TextBox();
            this.EditIPaddr = new System.Windows.Forms.TextBox();
            this.EditLogonTime = new System.Windows.Forms.TextBox();
            this.EditLogonLong = new System.Windows.Forms.TextBox();
            this.GroupBox11 = new System.Windows.Forms.GroupBox();
            this.Label20 = new System.Windows.Forms.Label();
            this.EditSayMsg = new System.Windows.Forms.TextBox();
            this.TabSheet2 = new System.Windows.Forms.TabPage();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label12 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.Label21 = new System.Windows.Forms.Label();
            this.Label32 = new System.Windows.Forms.Label();
            this.Label34 = new System.Windows.Forms.Label();
            this.EditLevel = new System.Windows.Forms.NumericUpDown();
            this.EditGold = new System.Windows.Forms.NumericUpDown();
            this.EditPKPoint = new System.Windows.Forms.NumericUpDown();
            this.EditExp = new System.Windows.Forms.NumericUpDown();
            this.EditMaxExp = new System.Windows.Forms.NumericUpDown();
            this.EditNGLevel = new System.Windows.Forms.NumericUpDown();
            this.EditExpSkill69 = new System.Windows.Forms.NumericUpDown();
            this.GroupBox6 = new System.Windows.Forms.GroupBox();
            this.CheckBoxGameMaster = new System.Windows.Forms.CheckBox();
            this.CheckBoxSuperMan = new System.Windows.Forms.CheckBox();
            this.CheckBoxObserver = new System.Windows.Forms.CheckBox();
            this.GroupBox9 = new System.Windows.Forms.GroupBox();
            this.Label26 = new System.Windows.Forms.Label();
            this.Label27 = new System.Windows.Forms.Label();
            this.Label28 = new System.Windows.Forms.Label();
            this.Label29 = new System.Windows.Forms.Label();
            this.Label19 = new System.Windows.Forms.Label();
            this.Label25 = new System.Windows.Forms.Label();
            this.Label30 = new System.Windows.Forms.Label();
            this.EditGameGold = new System.Windows.Forms.NumericUpDown();
            this.EditGamePoint = new System.Windows.Forms.NumericUpDown();
            this.EditCreditPoint = new System.Windows.Forms.NumericUpDown();
            this.EditBonusPoint = new System.Windows.Forms.NumericUpDown();
            this.EditEditBonusPointUsed = new System.Windows.Forms.NumericUpDown();
            this.EditGameGird = new System.Windows.Forms.NumericUpDown();
            this.EditGameDiaMond = new System.Windows.Forms.NumericUpDown();
            this.TabSheet3 = new System.Windows.Forms.TabPage();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label13 = new System.Windows.Forms.Label();
            this.Label14 = new System.Windows.Forms.Label();
            this.Label15 = new System.Windows.Forms.Label();
            this.Label16 = new System.Windows.Forms.Label();
            this.Label17 = new System.Windows.Forms.Label();
            this.Label18 = new System.Windows.Forms.Label();
            this.EditAC = new System.Windows.Forms.TextBox();
            this.EditMAC = new System.Windows.Forms.TextBox();
            this.EditDC = new System.Windows.Forms.TextBox();
            this.EditMC = new System.Windows.Forms.TextBox();
            this.EditSC = new System.Windows.Forms.TextBox();
            this.EditHP = new System.Windows.Forms.TextBox();
            this.EditMP = new System.Windows.Forms.TextBox();
            this.TabSheet4 = new System.Windows.Forms.TabPage();
            this.GroupBox7 = new System.Windows.Forms.GroupBox();
            this.GridUserItem = new System.Windows.Forms.DataGrid();
            this.TabSheet5 = new System.Windows.Forms.TabPage();
            this.GroupBox8 = new System.Windows.Forms.GroupBox();
            this.GridBagItem = new System.Windows.Forms.DataGrid();
            this.TabSheet6 = new System.Windows.Forms.TabPage();
            this.GroupBox10 = new System.Windows.Forms.GroupBox();
            this.GridStorageItem = new System.Windows.Forms.DataGrid();
            this.TabSheet7 = new System.Windows.Forms.TabPage();
            this.GroupBox12 = new System.Windows.Forms.GroupBox();
            this.Label22 = new System.Windows.Forms.Label();
            this.Label23 = new System.Windows.Forms.Label();
            this.Label24 = new System.Windows.Forms.Label();
            this.EditHeroName = new System.Windows.Forms.TextBox();
            this.EditHeroMap = new System.Windows.Forms.TextBox();
            this.EditHeroXY = new System.Windows.Forms.TextBox();
            this.GroupBox13 = new System.Windows.Forms.GroupBox();
            this.Label33 = new System.Windows.Forms.Label();
            this.Label35 = new System.Windows.Forms.Label();
            this.Label36 = new System.Windows.Forms.Label();
            this.Label37 = new System.Windows.Forms.Label();
            this.Label31 = new System.Windows.Forms.Label();
            this.Label38 = new System.Windows.Forms.Label();
            this.Label39 = new System.Windows.Forms.Label();
            this.EditHeroLevel = new System.Windows.Forms.NumericUpDown();
            this.EditHeroPKPoint = new System.Windows.Forms.NumericUpDown();
            this.EditHeroExp = new System.Windows.Forms.NumericUpDown();
            this.EditHeroMaxExp = new System.Windows.Forms.NumericUpDown();
            this.EditHeroLoyal = new System.Windows.Forms.NumericUpDown();
            this.EditHeroNGLevel = new System.Windows.Forms.NumericUpDown();
            this.EditHeroExpSkill69 = new System.Windows.Forms.NumericUpDown();
            this.TabSheet8 = new System.Windows.Forms.TabPage();
            this.GroupBox14 = new System.Windows.Forms.GroupBox();
            this.GridHeroUserItem = new System.Windows.Forms.DataGrid();
            this.TabSheet9 = new System.Windows.Forms.TabPage();
            this.GroupBox15 = new System.Windows.Forms.GroupBox();
            this.GridHeroBagItem = new System.Windows.Forms.DataGrid();
            this.GroupBox4 = new System.Windows.Forms.GroupBox();
            this.CheckBoxMonitor = new System.Windows.Forms.CheckBox();
            this.ButtonKick = new System.Windows.Forms.Button();
            this.GroupBox5 = new System.Windows.Forms.GroupBox();
            this.EditHumanStatus = new System.Windows.Forms.TextBox();
            this.ButtonSave = new System.Windows.Forms.Button();
            this.Timer = new System.Windows.Forms.Timer();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(627, 401);
            this.ClientSize  = new System.Drawing.Size(645, 335);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(134)));
            //this.Load += new System.EventHandler(this.FormCreate);
            this.AutoScroll = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Name = "frmHumanInfo";
            this.Text = "人物属性";
            this.PageControl1.Size  = new System.Drawing.Size(633, 241);
            this.PageControl1.Location  = new System.Drawing.Point(8, 8);
            this.PageControl1.SuspendLayout();
            this.PageControl1.SelectedTab = TabSheet2;
            this.PageControl1.TabIndex = 0;
            this.PageControl1.Enabled = true;
            this.PageControl1.Name = "PageControl1";
            this.TabSheet1.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet1.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet1.SuspendLayout();
            this.TabSheet1.Text = "人物信息";
            this.TabSheet1.Enabled = true;
            this.TabSheet1.Name = "TabSheet1";
            this.GroupBox1.Size  = new System.Drawing.Size(201, 193);
            this.GroupBox1.Location  = new System.Drawing.Point(8, 13);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.Text = "查看信息";
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.Label1.Size  = new System.Drawing.Size(54, 12);
            this.Label1.Location  = new System.Drawing.Point(8, 19);
            this.Label1.Text = "人物名称:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label2.Size  = new System.Drawing.Size(54, 12);
            this.Label2.Location  = new System.Drawing.Point(8, 43);
            this.Label2.Text = "所在地图:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label3.Size  = new System.Drawing.Size(54, 12);
            this.Label3.Location  = new System.Drawing.Point(8, 67);
            this.Label3.Text = "所在座标:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label4.Size  = new System.Drawing.Size(54, 12);
            this.Label4.Location  = new System.Drawing.Point(8, 91);
            this.Label4.Text = "登录帐号:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.Label5.Size  = new System.Drawing.Size(42, 12);
            this.Label5.Location  = new System.Drawing.Point(8, 115);
            this.Label5.Text = "登录IP:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label6.Size  = new System.Drawing.Size(54, 12);
            this.Label6.Location  = new System.Drawing.Point(8, 139);
            this.Label6.Text = "登录时间:";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.Label7.Size  = new System.Drawing.Size(54, 12);
            this.Label7.Location  = new System.Drawing.Point(8, 163);
            this.Label7.Text = "在线时长:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.EditName.Size  = new System.Drawing.Size(129, 20);
            this.EditName.Location  = new System.Drawing.Point(64, 16);
            this.EditName.TabIndex = 0;
            this.EditName.Text = "EditName";
            this.EditName.ReadOnly = true;
            this.EditName.Enabled = true;
            this.EditName.Name = "EditName";
            this.EditMap.Size  = new System.Drawing.Size(129, 20);
            this.EditMap.Location  = new System.Drawing.Point(64, 40);
            this.EditMap.TabIndex = 1;
            this.EditMap.Text = "Edit1";
            this.EditMap.ReadOnly = true;
            this.EditMap.Enabled = true;
            this.EditMap.Name = "EditMap";
            this.EditXY.Size  = new System.Drawing.Size(129, 20);
            this.EditXY.Location  = new System.Drawing.Point(64, 64);
            this.EditXY.TabIndex = 2;
            this.EditXY.Text = "Edit1";
            this.EditXY.ReadOnly = true;
            this.EditXY.Enabled = true;
            this.EditXY.Name = "EditXY";
            this.EditAccount.Size  = new System.Drawing.Size(129, 20);
            this.EditAccount.Location  = new System.Drawing.Point(64, 88);
            this.EditAccount.TabIndex = 3;
            this.EditAccount.Text = "Edit1";
            this.EditAccount.ReadOnly = true;
            this.EditAccount.Enabled = true;
            this.EditAccount.Name = "EditAccount";
            this.EditIPaddr.Size  = new System.Drawing.Size(129, 20);
            this.EditIPaddr.Location  = new System.Drawing.Point(64, 112);
            this.EditIPaddr.TabIndex = 4;
            this.EditIPaddr.Text = "Edit1";
            this.EditIPaddr.ReadOnly = true;
            this.EditIPaddr.Enabled = true;
            this.EditIPaddr.Name = "EditIPaddr";
            this.EditLogonTime.Size  = new System.Drawing.Size(129, 20);
            this.EditLogonTime.Location  = new System.Drawing.Point(64, 136);
            this.EditLogonTime.TabIndex = 5;
            this.EditLogonTime.Text = "Edit1";
            this.EditLogonTime.ReadOnly = true;
            this.EditLogonTime.Enabled = true;
            this.EditLogonTime.Name = "EditLogonTime";
            this.EditLogonLong.Size  = new System.Drawing.Size(129, 20);
            this.EditLogonLong.Location  = new System.Drawing.Point(64, 160);
            this.EditLogonLong.TabIndex = 6;
            this.EditLogonLong.Text = "Edit1";
            this.EditLogonLong.ReadOnly = true;
            this.EditLogonLong.Enabled = true;
            this.EditLogonLong.Name = "EditLogonLong";
            this.GroupBox11.Size  = new System.Drawing.Size(401, 185);
            this.GroupBox11.Location  = new System.Drawing.Point(216, 16);
            this.GroupBox11.SuspendLayout();
            this.GroupBox11.Text = "离线挂机";
            this.GroupBox11.TabIndex = 1;
            this.GroupBox11.Enabled = true;
            this.GroupBox11.Name = "GroupBox11";
            this.Label20.Size  = new System.Drawing.Size(60, 12);
            this.Label20.Location  = new System.Drawing.Point(8, 20);
            this.Label20.Text = "自动发言：";
            this.Label20.Enabled = true;
            this.Label20.Name = "Label20";
            this.EditSayMsg.Size  = new System.Drawing.Size(321, 20);
            this.EditSayMsg.Location  = new System.Drawing.Point(72, 16);
            this.EditSayMsg.TabIndex = 0;
            this.EditSayMsg.Text = "EditSayMsg";
            this.EditSayMsg.Enabled = true;
            this.EditSayMsg.Name = "EditSayMsg";
            this.TabSheet2.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet2.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet2.SuspendLayout();
            this.TabSheet2.Text = "普通数据";
            this.TabSheet2.ImageIndex = 1;
            this.TabSheet2.Enabled = true;
            this.TabSheet2.Name = "TabSheet2";
            this.GroupBox2.Size  = new System.Drawing.Size(177, 201);
            this.GroupBox2.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "可调属性";
            this.GroupBox2.TabIndex = 0;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label12.Size  = new System.Drawing.Size(30, 12);
            this.Label12.Location  = new System.Drawing.Point(8, 18);
            this.Label12.Text = "等级:";
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.Label8.Size  = new System.Drawing.Size(42, 12);
            this.Label8.Location  = new System.Drawing.Point(8, 42);
            this.Label8.Text = "金币数:";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.Label9.Size  = new System.Drawing.Size(42, 12);
            this.Label9.Location  = new System.Drawing.Point(8, 65);
            this.Label9.Text = "PK点数:";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label10.Size  = new System.Drawing.Size(54, 12);
            this.Label10.Location  = new System.Drawing.Point(8, 89);
            this.Label10.Text = "当前经验:";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.Label21.Size  = new System.Drawing.Size(54, 12);
            this.Label21.Location  = new System.Drawing.Point(8, 113);
            this.Label21.Text = "升级经验:";
            this.Label21.Enabled = true;
            this.Label21.Name = "Label21";
            this.Label32.Size  = new System.Drawing.Size(54, 12);
            this.Label32.Location  = new System.Drawing.Point(8, 136);
            this.Label32.Text = "内功等级:";
            this.Label32.Enabled = true;
            this.Label32.Name = "Label32";
            this.Label34.Size  = new System.Drawing.Size(54, 12);
            this.Label34.Location  = new System.Drawing.Point(8, 159);
            this.Label34.Text = "内功经验:";
            this.Label34.Enabled = true;
            this.Label34.Name = "Label34";
            ((System.ComponentModel.ISupportInitialize)(this.EditLevel)).BeginInit();
            this.EditLevel.Size  = new System.Drawing.Size(101, 21);
            this.EditLevel.Location  = new System.Drawing.Point(68, 15);
            this.EditLevel.Value = 10;
            this.EditLevel.TabIndex = 0;
            this.EditLevel.Name = "EditLevel";
            this.EditLevel.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditGold)).BeginInit();
            this.EditGold.Size  = new System.Drawing.Size(101, 21);
            this.EditGold.Location  = new System.Drawing.Point(68, 39);
            this.EditGold.Value = 10;
            this.EditGold.TabIndex = 1;
            this.EditGold.Name = "EditGold";
            this.EditGold.Enabled = true;
            this.EditGold.Increment = 1000;
            ((System.ComponentModel.ISupportInitialize)(this.EditPKPoint)).BeginInit();
            this.EditPKPoint.Size  = new System.Drawing.Size(101, 21);
            this.EditPKPoint.Location  = new System.Drawing.Point(68, 62);
            this.EditPKPoint.Value = 10;
            this.EditPKPoint.TabIndex = 2;
            this.EditPKPoint.Name = "EditPKPoint";
            this.EditPKPoint.Enabled = true;
            this.EditPKPoint.Increment = 50;
            ((System.ComponentModel.ISupportInitialize)(this.EditExp)).BeginInit();
            this.EditExp.Size  = new System.Drawing.Size(101, 21);
            this.EditExp.Location  = new System.Drawing.Point(68, 86);
            this.EditExp.Value = 10;
            this.EditExp.TabIndex = 3;
            this.EditExp.Name = "EditExp";
            this.EditExp.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditMaxExp)).BeginInit();
            this.EditMaxExp.Size  = new System.Drawing.Size(101, 21);
            this.EditMaxExp.Location  = new System.Drawing.Point(68, 110);
            this.EditMaxExp.Value = 10;
            this.EditMaxExp.TabIndex = 4;
            this.EditMaxExp.Name = "EditMaxExp";
            this.EditMaxExp.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditNGLevel)).BeginInit();
            this.EditNGLevel.Size  = new System.Drawing.Size(101, 21);
            this.EditNGLevel.Location  = new System.Drawing.Point(68, 133);
            this.EditNGLevel.Value = 1;
            this.EditNGLevel.TabIndex = 5;
            this.EditNGLevel.Name = "EditNGLevel";
            this.EditNGLevel.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditExpSkill69)).BeginInit();
            this.EditExpSkill69.Size  = new System.Drawing.Size(101, 21);
            this.EditExpSkill69.Location  = new System.Drawing.Point(68, 156);
            this.EditExpSkill69.Value = 0;
            this.EditExpSkill69.TabIndex = 6;
            this.EditExpSkill69.Name = "EditExpSkill69";
            this.EditExpSkill69.Enabled = false;
            this.toolTip1.SetToolTip(this.EditExpSkill69, "当前内功经验");
            this.GroupBox6.Size  = new System.Drawing.Size(153, 201);
            this.GroupBox6.Location  = new System.Drawing.Point(376, 8);
            this.GroupBox6.SuspendLayout();
            this.GroupBox6.Text = "人物状态";
            this.GroupBox6.TabIndex = 1;
            this.GroupBox6.Enabled = true;
            this.GroupBox6.Name = "GroupBox6";
            this.CheckBoxGameMaster.Size  = new System.Drawing.Size(113, 17);
            this.CheckBoxGameMaster.Location  = new System.Drawing.Point(8, 16);
            this.CheckBoxGameMaster.Text = "GM模式";
            this.CheckBoxGameMaster.TabIndex = 0;
            this.CheckBoxGameMaster.Enabled = true;
            this.CheckBoxGameMaster.Name = "CheckBoxGameMaster";
            this.CheckBoxSuperMan.Size  = new System.Drawing.Size(113, 17);
            this.CheckBoxSuperMan.Location  = new System.Drawing.Point(8, 32);
            this.CheckBoxSuperMan.Text = "无敌模式";
            this.CheckBoxSuperMan.TabIndex = 1;
            this.CheckBoxSuperMan.Enabled = true;
            this.CheckBoxSuperMan.Name = "CheckBoxSuperMan";
            this.CheckBoxObserver.Size  = new System.Drawing.Size(113, 17);
            this.CheckBoxObserver.Location  = new System.Drawing.Point(8, 48);
            this.CheckBoxObserver.Text = "隐身模式";
            this.CheckBoxObserver.TabIndex = 2;
            this.CheckBoxObserver.Enabled = true;
            this.CheckBoxObserver.Name = "CheckBoxObserver";
            this.GroupBox9.Size  = new System.Drawing.Size(177, 201);
            this.GroupBox9.Location  = new System.Drawing.Point(192, 8);
            this.GroupBox9.SuspendLayout();
            this.GroupBox9.Text = "可调属性";
            this.GroupBox9.TabIndex = 2;
            this.GroupBox9.Enabled = true;
            this.GroupBox9.Name = "GroupBox9";
            this.Label26.Size  = new System.Drawing.Size(42, 12);
            this.Label26.Location  = new System.Drawing.Point(8, 18);
            this.Label26.Text = "游戏币:";
            this.Label26.Enabled = true;
            this.Label26.Name = "Label26";
            this.Label27.Size  = new System.Drawing.Size(42, 12);
            this.Label27.Location  = new System.Drawing.Point(8, 42);
            this.Label27.Text = "游戏点:";
            this.Label27.Enabled = true;
            this.Label27.Name = "Label27";
            this.Label28.Size  = new System.Drawing.Size(42, 12);
            this.Label28.Location  = new System.Drawing.Point(8, 66);
            this.Label28.Text = "声望点:";
            this.Label28.Enabled = true;
            this.Label28.Name = "Label28";
            this.Label29.Size  = new System.Drawing.Size(54, 12);
            this.Label29.Location  = new System.Drawing.Point(8, 90);
            this.Label29.Text = "属性点一:";
            this.Label29.Enabled = true;
            this.Label29.Name = "Label29";
            this.Label19.Size  = new System.Drawing.Size(54, 12);
            this.Label19.Location  = new System.Drawing.Point(8, 114);
            this.Label19.Text = "属性点二:";
            this.Label19.Enabled = true;
            this.Label19.Name = "Label19";
            this.toolTip1.SetToolTip(this.Label19, "已分配属性点数。");
            this.Label25.Size  = new System.Drawing.Size(42, 12);
            this.Label25.Location  = new System.Drawing.Point(8, 138);
            this.Label25.Text = "金刚石:";
            this.Label25.Enabled = true;
            this.Label25.Name = "Label25";
            this.Label30.Size  = new System.Drawing.Size(42, 12);
            this.Label30.Location  = new System.Drawing.Point(8, 162);
            this.Label30.Text = "灵  符:";
            this.Label30.Enabled = true;
            this.Label30.Name = "Label30";
            ((System.ComponentModel.ISupportInitialize)(this.EditGameGold)).BeginInit();
            this.EditGameGold.Size  = new System.Drawing.Size(101, 21);
            this.EditGameGold.Location  = new System.Drawing.Point(68, 15);
            this.EditGameGold.Value = 10;
            this.EditGameGold.TabIndex = 0;
            this.EditGameGold.Name = "EditGameGold";
            this.EditGameGold.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditGamePoint)).BeginInit();
            this.EditGamePoint.Size  = new System.Drawing.Size(101, 21);
            this.EditGamePoint.Location  = new System.Drawing.Point(68, 39);
            this.EditGamePoint.Value = 10;
            this.EditGamePoint.TabIndex = 1;
            this.EditGamePoint.Name = "EditGamePoint";
            this.EditGamePoint.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditCreditPoint)).BeginInit();
            this.EditCreditPoint.Size  = new System.Drawing.Size(101, 21);
            this.EditCreditPoint.Location  = new System.Drawing.Point(68, 63);
            this.EditCreditPoint.Value = 10;
            this.EditCreditPoint.TabIndex = 2;
            this.EditCreditPoint.Name = "EditCreditPoint";
            this.EditCreditPoint.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditBonusPoint)).BeginInit();
            this.EditBonusPoint.Size  = new System.Drawing.Size(101, 21);
            this.EditBonusPoint.Location  = new System.Drawing.Point(68, 87);
            this.EditBonusPoint.Value = 10;
            this.EditBonusPoint.TabIndex = 3;
            this.EditBonusPoint.Name = "EditBonusPoint";
            this.EditBonusPoint.Enabled = true;
            this.toolTip1.SetToolTip(this.EditBonusPoint, "未分配属性点");
            ((System.ComponentModel.ISupportInitialize)(this.EditEditBonusPointUsed)).BeginInit();
            this.EditEditBonusPointUsed.Size  = new System.Drawing.Size(101, 21);
            this.EditEditBonusPointUsed.Location  = new System.Drawing.Point(68, 111);
            this.EditEditBonusPointUsed.Value = 10;
            this.EditEditBonusPointUsed.TabIndex = 4;
            this.EditEditBonusPointUsed.Name = "EditEditBonusPointUsed";
            this.EditEditBonusPointUsed.Enabled = false;
            this.toolTip1.SetToolTip(this.EditEditBonusPointUsed, "未分配属性点");
            ((System.ComponentModel.ISupportInitialize)(this.EditGameGird)).BeginInit();
            this.EditGameGird.Size  = new System.Drawing.Size(101, 21);
            this.EditGameGird.Location  = new System.Drawing.Point(68, 159);
            this.EditGameGird.Value = 10;
            this.EditGameGird.TabIndex = 5;
            this.EditGameGird.Name = "EditGameGird";
            this.EditGameGird.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditGameDiaMond)).BeginInit();
            this.EditGameDiaMond.Size  = new System.Drawing.Size(101, 21);
            this.EditGameDiaMond.Location  = new System.Drawing.Point(68, 135);
            this.EditGameDiaMond.Value = 10;
            this.EditGameDiaMond.TabIndex = 6;
            this.EditGameDiaMond.Name = "EditGameDiaMond";
            this.EditGameDiaMond.Enabled = true;
            this.TabSheet3.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet3.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet3.SuspendLayout();
            this.TabSheet3.Text = "属性点";
            this.TabSheet3.ImageIndex = 2;
            this.TabSheet3.Enabled = true;
            this.TabSheet3.Name = "TabSheet3";
            this.GroupBox3.Size  = new System.Drawing.Size(153, 193);
            this.GroupBox3.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.Text = "人物属性";
            this.GroupBox3.TabIndex = 0;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label11.Size  = new System.Drawing.Size(30, 12);
            this.Label11.Location  = new System.Drawing.Point(8, 19);
            this.Label11.Text = "防御:";
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label13.Size  = new System.Drawing.Size(30, 12);
            this.Label13.Location  = new System.Drawing.Point(8, 43);
            this.Label13.Text = "魔防:";
            this.Label13.Enabled = true;
            this.Label13.Name = "Label13";
            this.Label14.Size  = new System.Drawing.Size(42, 12);
            this.Label14.Location  = new System.Drawing.Point(8, 67);
            this.Label14.Text = "攻击力:";
            this.Label14.Enabled = true;
            this.Label14.Name = "Label14";
            this.Label15.Size  = new System.Drawing.Size(30, 12);
            this.Label15.Location  = new System.Drawing.Point(8, 91);
            this.Label15.Text = "魔法:";
            this.Label15.Enabled = true;
            this.Label15.Name = "Label15";
            this.Label16.Size  = new System.Drawing.Size(30, 12);
            this.Label16.Location  = new System.Drawing.Point(8, 115);
            this.Label16.Text = "道术:";
            this.Label16.Enabled = true;
            this.Label16.Name = "Label16";
            this.Label17.Size  = new System.Drawing.Size(42, 12);
            this.Label17.Location  = new System.Drawing.Point(8, 139);
            this.Label17.Text = "生命值:";
            this.Label17.Enabled = true;
            this.Label17.Name = "Label17";
            this.Label18.Size  = new System.Drawing.Size(42, 12);
            this.Label18.Location  = new System.Drawing.Point(8, 163);
            this.Label18.Text = "魔法值:";
            this.Label18.Enabled = true;
            this.Label18.Name = "Label18";
            this.EditAC.Size  = new System.Drawing.Size(81, 20);
            this.EditAC.Location  = new System.Drawing.Point(56, 16);
            this.EditAC.TabIndex = 0;
            this.EditAC.Text = "EditName";
            this.EditAC.ReadOnly = true;
            this.EditAC.Enabled = true;
            this.EditAC.Name = "EditAC";
            this.EditMAC.Size  = new System.Drawing.Size(81, 20);
            this.EditMAC.Location  = new System.Drawing.Point(56, 40);
            this.EditMAC.TabIndex = 1;
            this.EditMAC.Text = "EditName";
            this.EditMAC.ReadOnly = true;
            this.EditMAC.Enabled = true;
            this.EditMAC.Name = "EditMAC";
            this.EditDC.Size  = new System.Drawing.Size(81, 20);
            this.EditDC.Location  = new System.Drawing.Point(56, 64);
            this.EditDC.TabIndex = 2;
            this.EditDC.Text = "EditName";
            this.EditDC.ReadOnly = true;
            this.EditDC.Enabled = true;
            this.EditDC.Name = "EditDC";
            this.EditMC.Size  = new System.Drawing.Size(81, 20);
            this.EditMC.Location  = new System.Drawing.Point(56, 88);
            this.EditMC.TabIndex = 3;
            this.EditMC.Text = "EditName";
            this.EditMC.ReadOnly = true;
            this.EditMC.Enabled = true;
            this.EditMC.Name = "EditMC";
            this.EditSC.Size  = new System.Drawing.Size(81, 20);
            this.EditSC.Location  = new System.Drawing.Point(56, 112);
            this.EditSC.TabIndex = 4;
            this.EditSC.Text = "EditName";
            this.EditSC.ReadOnly = true;
            this.EditSC.Enabled = true;
            this.EditSC.Name = "EditSC";
            this.EditHP.Size  = new System.Drawing.Size(81, 20);
            this.EditHP.Location  = new System.Drawing.Point(56, 136);
            this.EditHP.TabIndex = 5;
            this.EditHP.Text = "EditName";
            this.EditHP.ReadOnly = true;
            this.EditHP.Enabled = true;
            this.EditHP.Name = "EditHP";
            this.EditMP.Size  = new System.Drawing.Size(81, 20);
            this.EditMP.Location  = new System.Drawing.Point(56, 160);
            this.EditMP.TabIndex = 6;
            this.EditMP.Text = "EditName";
            this.EditMP.ReadOnly = true;
            this.EditMP.Enabled = true;
            this.EditMP.Name = "EditMP";
            this.TabSheet4.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet4.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet4.SuspendLayout();
            this.TabSheet4.Text = "身上装备";
            this.TabSheet4.ImageIndex = 3;
            this.TabSheet4.Enabled = true;
            this.TabSheet4.Name = "TabSheet4";
            this.GroupBox7.Size  = new System.Drawing.Size(609, 201);
            this.GroupBox7.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox7.SuspendLayout();
            this.GroupBox7.Text = "装备列表";
            this.GroupBox7.TabIndex = 0;
            this.GroupBox7.Enabled = true;
            this.GroupBox7.Name = "GroupBox7";
            ((System.ComponentModel.ISupportInitialize)(this.GridUserItem)).BeginInit();
            this.GridUserItem.Size  = new System.Drawing.Size(593, 177);
            this.GridUserItem.Location  = new System.Drawing.Point(8, 16);
            this.GridUserItem.Name = "GridUserItem";
            this.GridUserItem.Enabled = true;
            //this.GridUserItem->PreferredColumnWidth = (int){55, 67, 63, 68, 45, 45, 44, 43, 46, 87};
            this.GridUserItem.TabIndex = 0;
            this.TabSheet5.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet5.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet5.SuspendLayout();
            this.TabSheet5.Text = "背包物品";
            this.TabSheet5.ImageIndex = 4;
            this.TabSheet5.Enabled = true;
            this.TabSheet5.Name = "TabSheet5";
            this.GroupBox8.Size  = new System.Drawing.Size(609, 201);
            this.GroupBox8.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox8.SuspendLayout();
            this.GroupBox8.Text = "装备列表";
            this.GroupBox8.TabIndex = 0;
            this.GroupBox8.Enabled = true;
            this.GroupBox8.Name = "GroupBox8";
            ((System.ComponentModel.ISupportInitialize)(this.GridBagItem)).BeginInit();
            this.GridBagItem.Size  = new System.Drawing.Size(593, 177);
            this.GridBagItem.Location  = new System.Drawing.Point(8, 16);
            this.GridBagItem.Name = "GridBagItem";
            this.GridBagItem.Enabled = true;
            //this.GridBagItem.PreferredColumnWidth = (int){55, 67, 63, 68, 45, 45, 44, 43, 46, 88};
            this.GridBagItem.TabIndex = 0;
            this.TabSheet6.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet6.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet6.SuspendLayout();
            this.TabSheet6.Text = "仓库物品";
            this.TabSheet6.ImageIndex = 5;
            this.TabSheet6.Enabled = true;
            this.TabSheet6.Name = "TabSheet6";
            this.GroupBox10.Size  = new System.Drawing.Size(609, 201);
            this.GroupBox10.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox10.SuspendLayout();
            this.GroupBox10.Text = "装备列表";
            this.GroupBox10.TabIndex = 0;
            this.GroupBox10.Enabled = true;
            this.GroupBox10.Name = "GroupBox10";
            ((System.ComponentModel.ISupportInitialize)(this.GridStorageItem)).BeginInit();
            this.GridStorageItem.Size  = new System.Drawing.Size(593, 177);
            this.GridStorageItem.Location  = new System.Drawing.Point(8, 16);
            this.GridStorageItem.Name = "GridStorageItem";
            this.GridStorageItem.Enabled = true;
            //this.GridStorageItem.PreferredColumnWidth = (int){55, 67, 63, 67, 45, 45, 44, 43, 46, 89};
            this.GridStorageItem.TabIndex = 0;
            this.TabSheet7.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet7.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet7.SuspendLayout();
            this.TabSheet7.Text = "英雄信息";
            this.TabSheet7.ImageIndex = 6;
            this.TabSheet7.Enabled = true;
            this.TabSheet7.Name = "TabSheet7";
            this.GroupBox12.Size  = new System.Drawing.Size(201, 193);
            this.GroupBox12.Location  = new System.Drawing.Point(8, 5);
            this.GroupBox12.SuspendLayout();
            this.GroupBox12.Text = "基本信息";
            this.GroupBox12.TabIndex = 0;
            this.GroupBox12.Enabled = true;
            this.GroupBox12.Name = "GroupBox12";
            this.Label22.Size  = new System.Drawing.Size(54, 12);
            this.Label22.Location  = new System.Drawing.Point(8, 19);
            this.Label22.Text = "英雄名称:";
            this.Label22.Enabled = true;
            this.Label22.Name = "Label22";
            this.Label23.Size  = new System.Drawing.Size(54, 12);
            this.Label23.Location  = new System.Drawing.Point(8, 43);
            this.Label23.Text = "所在地图:";
            this.Label23.Enabled = true;
            this.Label23.Name = "Label23";
            this.Label24.Size  = new System.Drawing.Size(54, 12);
            this.Label24.Location  = new System.Drawing.Point(8, 67);
            this.Label24.Text = "所在座标:";
            this.Label24.Enabled = true;
            this.Label24.Name = "Label24";
            this.EditHeroName.Size  = new System.Drawing.Size(129, 20);
            this.EditHeroName.Location  = new System.Drawing.Point(64, 16);
            this.EditHeroName.TabIndex = 0;
            this.EditHeroName.ReadOnly = true;
            this.EditHeroName.Enabled = true;
            this.EditHeroName.Name = "EditHeroName";
            this.EditHeroMap.Size  = new System.Drawing.Size(129, 20);
            this.EditHeroMap.Location  = new System.Drawing.Point(64, 40);
            this.EditHeroMap.TabIndex = 1;
            this.EditHeroMap.ReadOnly = true;
            this.EditHeroMap.Enabled = true;
            this.EditHeroMap.Name = "EditHeroMap";
            this.EditHeroXY.Size  = new System.Drawing.Size(129, 20);
            this.EditHeroXY.Location  = new System.Drawing.Point(64, 64);
            this.EditHeroXY.TabIndex = 2;
            this.EditHeroXY.ReadOnly = true;
            this.EditHeroXY.Enabled = true;
            this.EditHeroXY.Name = "EditHeroXY";
            this.GroupBox13.Size  = new System.Drawing.Size(177, 201);
            this.GroupBox13.Location  = new System.Drawing.Point(224, 8);
            this.GroupBox13.SuspendLayout();
            this.GroupBox13.Text = "可调属性";
            this.GroupBox13.TabIndex = 1;
            this.GroupBox13.Enabled = true;
            this.GroupBox13.Name = "GroupBox13";
            this.Label33.Size  = new System.Drawing.Size(30, 12);
            this.Label33.Location  = new System.Drawing.Point(8, 18);
            this.Label33.Text = "等级:";
            this.Label33.Enabled = true;
            this.Label33.Name = "Label33";
            this.Label35.Size  = new System.Drawing.Size(42, 12);
            this.Label35.Location  = new System.Drawing.Point(8, 42);
            this.Label35.Text = "PK点数:";
            this.Label35.Enabled = true;
            this.Label35.Name = "Label35";
            this.Label36.Size  = new System.Drawing.Size(54, 12);
            this.Label36.Location  = new System.Drawing.Point(8, 66);
            this.Label36.Text = "当前经验:";
            this.Label36.Enabled = true;
            this.Label36.Name = "Label36";
            this.Label37.Size  = new System.Drawing.Size(54, 12);
            this.Label37.Location  = new System.Drawing.Point(8, 90);
            this.Label37.Text = "升级经验:";
            this.Label37.Enabled = true;
            this.Label37.Name = "Label37";
            this.Label31.Size  = new System.Drawing.Size(42, 12);
            this.Label31.Location  = new System.Drawing.Point(8, 114);
            this.Label31.Text = "忠诚度:";
            this.Label31.Enabled = true;
            this.Label31.Name = "Label31";
            this.Label38.Size  = new System.Drawing.Size(54, 12);
            this.Label38.Location  = new System.Drawing.Point(8, 137);
            this.Label38.Text = "内功等级:";
            this.Label38.Enabled = true;
            this.Label38.Name = "Label38";
            this.Label39.Size  = new System.Drawing.Size(54, 12);
            this.Label39.Location  = new System.Drawing.Point(8, 160);
            this.Label39.Text = "内功经验:";
            this.Label39.Enabled = true;
            this.Label39.Name = "Label39";
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroLevel)).BeginInit();
            this.EditHeroLevel.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroLevel.Location  = new System.Drawing.Point(68, 15);
            this.EditHeroLevel.Value = 10;
            this.EditHeroLevel.TabIndex = 0;
            this.EditHeroLevel.Name = "EditHeroLevel";
            this.EditHeroLevel.Enabled = true;
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroPKPoint)).BeginInit();
            this.EditHeroPKPoint.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroPKPoint.Location  = new System.Drawing.Point(68, 39);
            this.EditHeroPKPoint.Value = 10;
            this.EditHeroPKPoint.TabIndex = 1;
            this.EditHeroPKPoint.Name = "EditHeroPKPoint";
            this.EditHeroPKPoint.Enabled = true;
            this.EditHeroPKPoint.Increment = 50;
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroExp)).BeginInit();
            this.EditHeroExp.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroExp.Location  = new System.Drawing.Point(68, 63);
            this.EditHeroExp.Value = 10;
            this.EditHeroExp.TabIndex = 2;
            this.EditHeroExp.Name = "EditHeroExp";
            this.EditHeroExp.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroMaxExp)).BeginInit();
            this.EditHeroMaxExp.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroMaxExp.Location  = new System.Drawing.Point(68, 87);
            this.EditHeroMaxExp.Value = 10;
            this.EditHeroMaxExp.TabIndex = 3;
            this.EditHeroMaxExp.Name = "EditHeroMaxExp";
            this.EditHeroMaxExp.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroLoyal)).BeginInit();
            this.EditHeroLoyal.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroLoyal.Location  = new System.Drawing.Point(68, 111);
            this.EditHeroLoyal.Value = 10;
            this.EditHeroLoyal.TabIndex = 4;
            this.EditHeroLoyal.Name = "EditHeroLoyal";
            this.EditHeroLoyal.Enabled = true;
            this.toolTip1.SetToolTip(this.EditHeroLoyal, "100为忠诚度1%");
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroNGLevel)).BeginInit();
            this.EditHeroNGLevel.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroNGLevel.Location  = new System.Drawing.Point(68, 134);
            this.EditHeroNGLevel.Value = 1;
            this.EditHeroNGLevel.TabIndex = 5;
            this.EditHeroNGLevel.Name = "EditHeroNGLevel";
            this.EditHeroNGLevel.Enabled = false;
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroExpSkill69)).BeginInit();
            this.EditHeroExpSkill69.Size  = new System.Drawing.Size(101, 21);
            this.EditHeroExpSkill69.Location  = new System.Drawing.Point(68, 157);
            this.EditHeroExpSkill69.Value = 0;
            this.EditHeroExpSkill69.TabIndex = 6;
            this.EditHeroExpSkill69.Name = "EditHeroExpSkill69";
            this.EditHeroExpSkill69.Enabled = false;
            this.toolTip1.SetToolTip(this.EditHeroExpSkill69, "当前内功经验");
            this.TabSheet8.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet8.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet8.SuspendLayout();
            this.TabSheet8.Text = "英雄装备";
            this.TabSheet8.ImageIndex = 7;
            this.TabSheet8.Enabled = true;
            this.TabSheet8.Name = "TabSheet8";
            this.GroupBox14.Size  = new System.Drawing.Size(609, 201);
            this.GroupBox14.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox14.SuspendLayout();
            this.GroupBox14.Text = "装备列表";
            this.GroupBox14.TabIndex = 0;
            this.GroupBox14.Enabled = true;
            this.GroupBox14.Name = "GroupBox14";
            ((System.ComponentModel.ISupportInitialize)(this.GridHeroUserItem)).BeginInit();
            this.GridHeroUserItem.Size  = new System.Drawing.Size(593, 177);
            this.GridHeroUserItem.Location  = new System.Drawing.Point(8, 16);
            //this.GridHeroUserItem.AccessibilityObjectName = "GridHeroUserItem";
            this.GridHeroUserItem.Enabled = true;
            //this.GridHeroUserItem->PreferredColumnWidth = (int){55, 67, 63, 68, 45, 45, 44, 43, 46, 87};
            this.GridHeroUserItem.TabIndex = 0;
            this.TabSheet9.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet9.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet9.SuspendLayout();
            this.TabSheet9.Text = "英雄背包";
            this.TabSheet9.ImageIndex = 8;
            this.TabSheet9.Enabled = true;
            this.TabSheet9.Name = "TabSheet9";
            this.GroupBox15.Size  = new System.Drawing.Size(609, 201);
            this.GroupBox15.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox15.SuspendLayout();
            this.GroupBox15.Text = "装备列表";
            this.GroupBox15.TabIndex = 0;
            this.GroupBox15.Enabled = true;
            this.GroupBox15.Name = "GroupBox15";
            ((System.ComponentModel.ISupportInitialize)(this.GridHeroBagItem)).BeginInit();
            this.GridHeroBagItem.Size  = new System.Drawing.Size(593, 177);
            this.GridHeroBagItem.Location  = new System.Drawing.Point(8, 16);
            this.GridHeroBagItem.Name = "GridHeroBagItem";
            this.GridHeroBagItem.Enabled = true;
            //this.GridHeroBagItem.PreferredColumnWidth = (int){55, 67, 63, 68, 45, 45, 44, 43, 46, 88};
            this.GridHeroBagItem.TabIndex = 0;
            this.GroupBox4.Size  = new System.Drawing.Size(145, 73);
            this.GroupBox4.Location  = new System.Drawing.Point(8, 256);
            this.GroupBox4.SuspendLayout();
            this.GroupBox4.Text = "控制";
            this.GroupBox4.TabIndex = 1;
            this.GroupBox4.Enabled = true;
            this.GroupBox4.Name = "GroupBox4";
            this.CheckBoxMonitor.Size  = new System.Drawing.Size(89, 17);
            this.CheckBoxMonitor.Location  = new System.Drawing.Point(8, 16);
            this.CheckBoxMonitor.Text = "实时监控";
            this.CheckBoxMonitor.TabIndex = 0;
            this.CheckBoxMonitor.Enabled = true;
           // this.CheckBoxMonitor.Click += new System.EventHandler(this.CheckBoxMonitorClick);
            this.CheckBoxMonitor.Name = "CheckBoxMonitor";
            this.ButtonKick.Size  = new System.Drawing.Size(65, 25);
            this.ButtonKick.Location  = new System.Drawing.Point(8, 40);
           // this.ButtonKick.Click += new System.EventHandler(this.ButtonKickClick);
            this.ButtonKick.TabIndex = 1;
            this.ButtonKick.Name = "ButtonKick";
            this.ButtonKick.Enabled = true;
            this.ButtonKick.Text = "踢下线";
           // this.ButtonKick.BackColor = clBtnFace;
            this.GroupBox5.Size  = new System.Drawing.Size(121, 73);
            this.GroupBox5.Location  = new System.Drawing.Point(160, 256);
            this.GroupBox5.SuspendLayout();
            this.GroupBox5.Text = "主体当前状态";
            this.GroupBox5.TabIndex = 2;
            this.GroupBox5.Enabled = true;
            this.GroupBox5.Name = "GroupBox5";
            this.EditHumanStatus.Size  = new System.Drawing.Size(105, 20);
            this.EditHumanStatus.Location  = new System.Drawing.Point(8, 24);
            this.EditHumanStatus.TabIndex = 0;
            this.EditHumanStatus.ReadOnly = true;
            this.EditHumanStatus.Enabled = true;
            this.EditHumanStatus.Name = "EditHumanStatus";
            this.ButtonSave.Size  = new System.Drawing.Size(65, 25);
            this.ButtonSave.Location  = new System.Drawing.Point(336, 296);
           // this.ButtonSave.Click += new System.EventHandler(this.ButtonSaveClick);
            this.ButtonSave.TabIndex = 3;
            this.ButtonSave.Name = "ButtonSave";
            this.ButtonSave.Enabled = true;
            this.ButtonSave.Text = "修改数据";
            //this.ButtonSave.BackColor = clBtnFace;
            //this.Timer.Tick += new System.EventHandler(this.TimerTimer);
            this.Timer.Enabled = false;
            this.GroupBox1.Controls.Add(Label1);
            this.GroupBox1.Controls.Add(Label2);
            this.GroupBox1.Controls.Add(Label3);
            this.GroupBox1.Controls.Add(Label4);
            this.GroupBox1.Controls.Add(Label5);
            this.GroupBox1.Controls.Add(Label6);
            this.GroupBox1.Controls.Add(Label7);
            this.GroupBox1.Controls.Add(EditName);
            this.GroupBox1.Controls.Add(EditMap);
            this.GroupBox1.Controls.Add(EditXY);
            this.GroupBox1.Controls.Add(EditAccount);
            this.GroupBox1.Controls.Add(EditIPaddr);
            this.GroupBox1.Controls.Add(EditLogonTime);
            this.GroupBox1.Controls.Add(EditLogonLong);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox11.Controls.Add(Label20);
            this.GroupBox11.Controls.Add(EditSayMsg);
            this.GroupBox11.ResumeLayout(false);
            this.TabSheet1.Controls.Add(GroupBox1);
            this.TabSheet1.Controls.Add(GroupBox11);
            this.TabSheet1.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label12);
            this.GroupBox2.Controls.Add(Label8);
            this.GroupBox2.Controls.Add(Label9);
            this.GroupBox2.Controls.Add(Label10);
            this.GroupBox2.Controls.Add(Label21);
            this.GroupBox2.Controls.Add(Label32);
            this.GroupBox2.Controls.Add(Label34);
            this.GroupBox2.Controls.Add(EditLevel);
            this.GroupBox2.Controls.Add(EditGold);
            this.GroupBox2.Controls.Add(EditPKPoint);
            this.GroupBox2.Controls.Add(EditExp);
            this.GroupBox2.Controls.Add(EditMaxExp);
            this.GroupBox2.Controls.Add(EditNGLevel);
            this.GroupBox2.Controls.Add(EditExpSkill69);
            ((System.ComponentModel.ISupportInitialize)(this.EditLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditGold)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditPKPoint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditExp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditMaxExp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditNGLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditExpSkill69)).EndInit();
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox6.Controls.Add(CheckBoxGameMaster);
            this.GroupBox6.Controls.Add(CheckBoxSuperMan);
            this.GroupBox6.Controls.Add(CheckBoxObserver);
            this.GroupBox6.ResumeLayout(false);
            this.GroupBox9.Controls.Add(Label26);
            this.GroupBox9.Controls.Add(Label27);
            this.GroupBox9.Controls.Add(Label28);
            this.GroupBox9.Controls.Add(Label29);
            this.GroupBox9.Controls.Add(Label19);
            this.GroupBox9.Controls.Add(Label25);
            this.GroupBox9.Controls.Add(Label30);
            this.GroupBox9.Controls.Add(EditGameGold);
            this.GroupBox9.Controls.Add(EditGamePoint);
            this.GroupBox9.Controls.Add(EditCreditPoint);
            this.GroupBox9.Controls.Add(EditBonusPoint);
            this.GroupBox9.Controls.Add(EditEditBonusPointUsed);
            this.GroupBox9.Controls.Add(EditGameGird);
            this.GroupBox9.Controls.Add(EditGameDiaMond);
            ((System.ComponentModel.ISupportInitialize)(this.EditGameGold)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditGamePoint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditCreditPoint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditBonusPoint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditEditBonusPointUsed)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditGameGird)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditGameDiaMond)).EndInit();
            this.GroupBox9.ResumeLayout(false);
            this.TabSheet2.Controls.Add(GroupBox2);
            this.TabSheet2.Controls.Add(GroupBox6);
            this.TabSheet2.Controls.Add(GroupBox9);
            this.TabSheet2.ResumeLayout(false);
            this.GroupBox3.Controls.Add(Label11);
            this.GroupBox3.Controls.Add(Label13);
            this.GroupBox3.Controls.Add(Label14);
            this.GroupBox3.Controls.Add(Label15);
            this.GroupBox3.Controls.Add(Label16);
            this.GroupBox3.Controls.Add(Label17);
            this.GroupBox3.Controls.Add(Label18);
            this.GroupBox3.Controls.Add(EditAC);
            this.GroupBox3.Controls.Add(EditMAC);
            this.GroupBox3.Controls.Add(EditDC);
            this.GroupBox3.Controls.Add(EditMC);
            this.GroupBox3.Controls.Add(EditSC);
            this.GroupBox3.Controls.Add(EditHP);
            this.GroupBox3.Controls.Add(EditMP);
            this.GroupBox3.ResumeLayout(false);
            this.TabSheet3.Controls.Add(GroupBox3);
            this.TabSheet3.ResumeLayout(false);
            this.GroupBox7.Controls.Add(GridUserItem);
            ((System.ComponentModel.ISupportInitialize)(this.GridUserItem)).EndInit();
            this.GroupBox7.ResumeLayout(false);
            this.TabSheet4.Controls.Add(GroupBox7);
            this.TabSheet4.ResumeLayout(false);
            this.GroupBox8.Controls.Add(GridBagItem);
            ((System.ComponentModel.ISupportInitialize)(this.GridBagItem)).EndInit();
            this.GroupBox8.ResumeLayout(false);
            this.TabSheet5.Controls.Add(GroupBox8);
            this.TabSheet5.ResumeLayout(false);
            this.GroupBox10.Controls.Add(GridStorageItem);
            ((System.ComponentModel.ISupportInitialize)(this.GridStorageItem)).EndInit();
            this.GroupBox10.ResumeLayout(false);
            this.TabSheet6.Controls.Add(GroupBox10);
            this.TabSheet6.ResumeLayout(false);
            this.GroupBox12.Controls.Add(Label22);
            this.GroupBox12.Controls.Add(Label23);
            this.GroupBox12.Controls.Add(Label24);
            this.GroupBox12.Controls.Add(EditHeroName);
            this.GroupBox12.Controls.Add(EditHeroMap);
            this.GroupBox12.Controls.Add(EditHeroXY);
            this.GroupBox12.ResumeLayout(false);
            this.GroupBox13.Controls.Add(Label33);
            this.GroupBox13.Controls.Add(Label35);
            this.GroupBox13.Controls.Add(Label36);
            this.GroupBox13.Controls.Add(Label37);
            this.GroupBox13.Controls.Add(Label31);
            this.GroupBox13.Controls.Add(Label38);
            this.GroupBox13.Controls.Add(Label39);
            this.GroupBox13.Controls.Add(EditHeroLevel);
            this.GroupBox13.Controls.Add(EditHeroPKPoint);
            this.GroupBox13.Controls.Add(EditHeroExp);
            this.GroupBox13.Controls.Add(EditHeroMaxExp);
            this.GroupBox13.Controls.Add(EditHeroLoyal);
            this.GroupBox13.Controls.Add(EditHeroNGLevel);
            this.GroupBox13.Controls.Add(EditHeroExpSkill69);
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroPKPoint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroExp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroMaxExp)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroLoyal)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroNGLevel)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.EditHeroExpSkill69)).EndInit();
            this.GroupBox13.ResumeLayout(false);
            this.TabSheet7.Controls.Add(GroupBox12);
            this.TabSheet7.Controls.Add(GroupBox13);
            this.TabSheet7.ResumeLayout(false);
            this.GroupBox14.Controls.Add(GridHeroUserItem);
            ((System.ComponentModel.ISupportInitialize)(this.GridHeroUserItem)).EndInit();
            this.GroupBox14.ResumeLayout(false);
            this.TabSheet8.Controls.Add(GroupBox14);
            this.TabSheet8.ResumeLayout(false);
            this.GroupBox15.Controls.Add(GridHeroBagItem);
            ((System.ComponentModel.ISupportInitialize)(this.GridHeroBagItem)).EndInit();
            this.GroupBox15.ResumeLayout(false);
            this.TabSheet9.Controls.Add(GroupBox15);
            this.TabSheet9.ResumeLayout(false);
            this.PageControl1.Controls.Add(TabSheet1);
            this.PageControl1.Controls.Add(TabSheet2);
            this.PageControl1.Controls.Add(TabSheet3);
            this.PageControl1.Controls.Add(TabSheet4);
            this.PageControl1.Controls.Add(TabSheet5);
            this.PageControl1.Controls.Add(TabSheet6);
            this.PageControl1.Controls.Add(TabSheet7);
            this.PageControl1.Controls.Add(TabSheet8);
            this.PageControl1.Controls.Add(TabSheet9);
            this.PageControl1.ResumeLayout(false);
            this.GroupBox4.Controls.Add(CheckBoxMonitor);
            this.GroupBox4.Controls.Add(ButtonKick);
            this.GroupBox4.ResumeLayout(false);
            this.GroupBox5.Controls.Add(EditHumanStatus);
            this.GroupBox5.ResumeLayout(false);
            this.Controls.Add(PageControl1);
            this.Controls.Add(GroupBox4);
            this.Controls.Add(GroupBox5);
            this.Controls.Add(ButtonSave);
            this.ResumeLayout(false);
        }
#endregion

    }
}
