namespace M2Server
{
  partial class TfrmViewKernelInfo
    {
        public System.Windows.Forms.TabControl PageControl1;
        public System.Windows.Forms.TabPage TabSheet4;
        public System.Windows.Forms.GroupBox GroupBox6;
        public System.Windows.Forms.Label Label25;
        public System.Windows.Forms.Label Label26;
        public System.Windows.Forms.TextBox EditAllocMemCount;
        public System.Windows.Forms.TextBox EditAllocMemSize;
        public System.Windows.Forms.TabPage TabSheet1;
        public System.Windows.Forms.GroupBox GroupBox1;
        public System.Windows.Forms.Label Label1;
        public System.Windows.Forms.Label Label2;
        public System.Windows.Forms.Label Label3;
        public System.Windows.Forms.Label Label4;
        public System.Windows.Forms.TextBox EditLoadHumanDBCount;
        public System.Windows.Forms.TextBox EditLoadHumanDBErrorCoun;
        public System.Windows.Forms.TextBox EditSaveHumanDBCount;
        public System.Windows.Forms.TextBox EditHumanDBQueryID;
        public System.Windows.Forms.GroupBox GroupBox4;
        public System.Windows.Forms.Label Label7;
        public System.Windows.Forms.Label Label8;
        public System.Windows.Forms.TextBox EditItemNumber;
        public System.Windows.Forms.TextBox EditItemNumberEx;
        public System.Windows.Forms.TabPage TabSheet2;
        public System.Windows.Forms.GroupBox GroupBox2;
        public System.Windows.Forms.Label Label5;
        public System.Windows.Forms.Label Label6;
        public System.Windows.Forms.TextBox EditWinLotteryCount;
        public System.Windows.Forms.TextBox EditNoWinLotteryCount;
        public System.Windows.Forms.GroupBox GroupBox3;
        public System.Windows.Forms.Label Label9;
        public System.Windows.Forms.Label Label10;
        public System.Windows.Forms.Label Label11;
        public System.Windows.Forms.Label Label12;
        public System.Windows.Forms.Label Label13;
        public System.Windows.Forms.Label Label14;
        public System.Windows.Forms.TextBox EditWinLotteryLevel1;
        public System.Windows.Forms.TextBox EditWinLotteryLevel2;
        public System.Windows.Forms.TextBox EditWinLotteryLevel3;
        public System.Windows.Forms.TextBox EditWinLotteryLevel4;
        public System.Windows.Forms.TextBox EditWinLotteryLevel5;
        public System.Windows.Forms.TextBox EditWinLotteryLevel6;
        public System.Windows.Forms.TabPage TabSheet3;
        public System.Windows.Forms.GroupBox GroupBox5;
        public System.Windows.Forms.Label Label15;
        public System.Windows.Forms.Label Label16;
        public System.Windows.Forms.Label Label17;
        public System.Windows.Forms.Label Label18;
        public System.Windows.Forms.Label Label19;
        public System.Windows.Forms.Label Label20;
        public System.Windows.Forms.Label Label21;
        public System.Windows.Forms.Label Label22;
        public System.Windows.Forms.Label Label23;
        public System.Windows.Forms.Label Label24;
        public System.Windows.Forms.TextBox EditGlobalVal1;
        public System.Windows.Forms.TextBox EditGlobalVal2;
        public System.Windows.Forms.TextBox EditGlobalVal3;
        public System.Windows.Forms.TextBox EditGlobalVal4;
        public System.Windows.Forms.TextBox EditGlobalVal5;
        public System.Windows.Forms.TextBox EditGlobalVal6;
        public System.Windows.Forms.TextBox EditGlobalVal7;
        public System.Windows.Forms.TextBox EditGlobalVal8;
        public System.Windows.Forms.TextBox EditGlobalVal9;
        public System.Windows.Forms.TextBox EditGlobalVal10;
        public System.Windows.Forms.TabPage TabSheet5;
        public System.Windows.Forms.GroupBox GroupBox7;
        public System.Windows.Forms.DataGrid GridThread;
        public System.Windows.Forms.Timer Timer;
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.ToolTip toolTip1 = null;

        // Clean up any resources being used.
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

#region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(this.GetType());
            this.components = new System.ComponentModel.Container();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.PageControl1 = new System.Windows.Forms.TabControl();
            this.TabSheet4 = new System.Windows.Forms.TabPage();
            this.GroupBox6 = new System.Windows.Forms.GroupBox();
            this.Label25 = new System.Windows.Forms.Label();
            this.Label26 = new System.Windows.Forms.Label();
            this.EditAllocMemCount = new System.Windows.Forms.TextBox();
            this.EditAllocMemSize = new System.Windows.Forms.TextBox();
            this.TabSheet1 = new System.Windows.Forms.TabPage();
            this.GroupBox1 = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.EditLoadHumanDBCount = new System.Windows.Forms.TextBox();
            this.EditLoadHumanDBErrorCoun = new System.Windows.Forms.TextBox();
            this.EditSaveHumanDBCount = new System.Windows.Forms.TextBox();
            this.EditHumanDBQueryID = new System.Windows.Forms.TextBox();
            this.GroupBox4 = new System.Windows.Forms.GroupBox();
            this.Label7 = new System.Windows.Forms.Label();
            this.Label8 = new System.Windows.Forms.Label();
            this.EditItemNumber = new System.Windows.Forms.TextBox();
            this.EditItemNumberEx = new System.Windows.Forms.TextBox();
            this.TabSheet2 = new System.Windows.Forms.TabPage();
            this.GroupBox2 = new System.Windows.Forms.GroupBox();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label6 = new System.Windows.Forms.Label();
            this.EditWinLotteryCount = new System.Windows.Forms.TextBox();
            this.EditNoWinLotteryCount = new System.Windows.Forms.TextBox();
            this.GroupBox3 = new System.Windows.Forms.GroupBox();
            this.Label9 = new System.Windows.Forms.Label();
            this.Label10 = new System.Windows.Forms.Label();
            this.Label11 = new System.Windows.Forms.Label();
            this.Label12 = new System.Windows.Forms.Label();
            this.Label13 = new System.Windows.Forms.Label();
            this.Label14 = new System.Windows.Forms.Label();
            this.EditWinLotteryLevel1 = new System.Windows.Forms.TextBox();
            this.EditWinLotteryLevel2 = new System.Windows.Forms.TextBox();
            this.EditWinLotteryLevel3 = new System.Windows.Forms.TextBox();
            this.EditWinLotteryLevel4 = new System.Windows.Forms.TextBox();
            this.EditWinLotteryLevel5 = new System.Windows.Forms.TextBox();
            this.EditWinLotteryLevel6 = new System.Windows.Forms.TextBox();
            this.TabSheet3 = new System.Windows.Forms.TabPage();
            this.GroupBox5 = new System.Windows.Forms.GroupBox();
            this.Label15 = new System.Windows.Forms.Label();
            this.Label16 = new System.Windows.Forms.Label();
            this.Label17 = new System.Windows.Forms.Label();
            this.Label18 = new System.Windows.Forms.Label();
            this.Label19 = new System.Windows.Forms.Label();
            this.Label20 = new System.Windows.Forms.Label();
            this.Label21 = new System.Windows.Forms.Label();
            this.Label22 = new System.Windows.Forms.Label();
            this.Label23 = new System.Windows.Forms.Label();
            this.Label24 = new System.Windows.Forms.Label();
            this.EditGlobalVal1 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal2 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal3 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal4 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal5 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal6 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal7 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal8 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal9 = new System.Windows.Forms.TextBox();
            this.EditGlobalVal10 = new System.Windows.Forms.TextBox();
            this.TabSheet5 = new System.Windows.Forms.TabPage();
            this.GroupBox7 = new System.Windows.Forms.GroupBox();
            this.GridThread = new System.Windows.Forms.DataGrid();
            this.Timer = new System.Windows.Forms.Timer();
            this.SuspendLayout();
            this.Location  = new System.Drawing.Point(445, 437);
            this.ClientSize  = new System.Drawing.Size(474, 226);
            this.Font  = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point ,((byte)(134)));
            //this.Closed += new System.EventHandler(this.FormClose);
            this.Name = "frmViewKernelInfo";
            this.Text = "内核数据查看";
            //this.Load += new System.EventHandler(this.FormCreate);
            this.AutoScroll = true;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.PageControl1.Size  = new System.Drawing.Size(457, 209);
            this.PageControl1.Location  = new System.Drawing.Point(8, 8);
            this.PageControl1.SuspendLayout();
            this.PageControl1.SelectedTab = TabSheet1;
            this.PageControl1.TabIndex = 0;
            this.PageControl1.Enabled = true;
            this.PageControl1.Name = "PageControl1";
            this.TabSheet4.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet4.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet4.SuspendLayout();
            this.TabSheet4.Text = "系统数据";
            this.TabSheet4.ImageIndex = 3;
            this.TabSheet4.Enabled = true;
            this.TabSheet4.Name = "TabSheet4";
            this.GroupBox6.Size  = new System.Drawing.Size(193, 97);
            this.GroupBox6.Location  = new System.Drawing.Point(8, 8);
            this.GroupBox6.SuspendLayout();
            this.GroupBox6.Text = "内存分配";
            this.GroupBox6.TabIndex = 0;
            this.GroupBox6.Enabled = true;
            this.GroupBox6.Name = "GroupBox6";
            this.Label25.Size  = new System.Drawing.Size(54, 12);
            this.Label25.Location  = new System.Drawing.Point(8, 20);
            this.Label25.Text = "内存大小:";
            this.Label25.Enabled = true;
            this.Label25.Name = "Label25";
            this.Label26.Size  = new System.Drawing.Size(66, 12);
            this.Label26.Location  = new System.Drawing.Point(8, 44);
            this.Label26.Text = "内存块数量:";
            this.Label26.Enabled = true;
            this.Label26.Name = "Label26";
            this.EditAllocMemCount.Size  = new System.Drawing.Size(73, 20);
            this.EditAllocMemCount.Location  = new System.Drawing.Point(88, 40);
            this.EditAllocMemCount.TabIndex = 0;
            this.EditAllocMemCount.ReadOnly = true;
            this.EditAllocMemCount.Enabled = true;
            this.EditAllocMemCount.Name = "EditAllocMemCount";
            this.EditAllocMemSize.Size  = new System.Drawing.Size(73, 20);
            this.EditAllocMemSize.Location  = new System.Drawing.Point(88, 16);
            this.EditAllocMemSize.TabIndex = 1;
            this.EditAllocMemSize.ReadOnly = true;
            this.EditAllocMemSize.Enabled = true;
            this.EditAllocMemSize.Name = "EditAllocMemSize";
            this.TabSheet1.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet1.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet1.SuspendLayout();
            this.TabSheet1.Text = "游戏数据";
            this.TabSheet1.Enabled = true;
            this.TabSheet1.Name = "TabSheet1";
            this.GroupBox1.Size  = new System.Drawing.Size(153, 121);
            this.GroupBox1.Location  = new System.Drawing.Point(8, 4);
            this.GroupBox1.SuspendLayout();
            this.GroupBox1.Text = "游戏数据库";
            this.GroupBox1.TabIndex = 0;
            this.GroupBox1.Enabled = true;
            this.GroupBox1.Name = "GroupBox1";
            this.Label1.Size  = new System.Drawing.Size(78, 12);
            this.Label1.Location  = new System.Drawing.Point(8, 20);
            this.Label1.Text = "读取请求次数:";
            this.Label1.Enabled = true;
            this.Label1.Name = "Label1";
            this.Label2.Size  = new System.Drawing.Size(78, 12);
            this.Label2.Location  = new System.Drawing.Point(8, 44);
            this.Label2.Text = "读取失败次数:";
            this.Label2.Enabled = true;
            this.Label2.Name = "Label2";
            this.Label3.Size  = new System.Drawing.Size(78, 12);
            this.Label3.Location  = new System.Drawing.Point(8, 68);
            this.Label3.Text = "保存请求次数:";
            this.Label3.Enabled = true;
            this.Label3.Name = "Label3";
            this.Label4.Size  = new System.Drawing.Size(78, 12);
            this.Label4.Location  = new System.Drawing.Point(8, 92);
            this.Label4.Text = "请求标识数字:";
            this.Label4.Enabled = true;
            this.Label4.Name = "Label4";
            this.EditLoadHumanDBCount.Size  = new System.Drawing.Size(57, 20);
            this.EditLoadHumanDBCount.Location  = new System.Drawing.Point(88, 16);
            this.EditLoadHumanDBCount.TabIndex = 0;
            this.EditLoadHumanDBCount.ReadOnly = true;
            this.EditLoadHumanDBCount.Enabled = true;
            this.EditLoadHumanDBCount.Name = "EditLoadHumanDBCount";
            this.EditLoadHumanDBErrorCoun.Size  = new System.Drawing.Size(57, 20);
            this.EditLoadHumanDBErrorCoun.Location  = new System.Drawing.Point(88, 40);
            this.EditLoadHumanDBErrorCoun.TabIndex = 1;
            this.EditLoadHumanDBErrorCoun.ReadOnly = true;
            this.EditLoadHumanDBErrorCoun.Enabled = true;
            this.EditLoadHumanDBErrorCoun.Name = "EditLoadHumanDBErrorCoun";
            this.EditSaveHumanDBCount.Size  = new System.Drawing.Size(57, 20);
            this.EditSaveHumanDBCount.Location  = new System.Drawing.Point(88, 64);
            this.EditSaveHumanDBCount.TabIndex = 2;
            this.EditSaveHumanDBCount.ReadOnly = true;
            this.EditSaveHumanDBCount.Enabled = true;
            this.EditSaveHumanDBCount.Name = "EditSaveHumanDBCount";
            this.EditHumanDBQueryID.Size  = new System.Drawing.Size(57, 20);
            this.EditHumanDBQueryID.Location  = new System.Drawing.Point(88, 88);
            this.EditHumanDBQueryID.TabIndex = 3;
            this.EditHumanDBQueryID.ReadOnly = true;
            this.EditHumanDBQueryID.Enabled = true;
            this.EditHumanDBQueryID.Name = "EditHumanDBQueryID";
            this.GroupBox4.Size  = new System.Drawing.Size(177, 69);
            this.GroupBox4.Location  = new System.Drawing.Point(168, 4);
            this.GroupBox4.SuspendLayout();
            this.GroupBox4.Text = "物品系列号";
            this.GroupBox4.TabIndex = 1;
            this.GroupBox4.Enabled = true;
            this.GroupBox4.Name = "GroupBox4";
            this.Label7.Size  = new System.Drawing.Size(78, 12);
            this.Label7.Location  = new System.Drawing.Point(8, 20);
            this.Label7.Text = "怪物掉落物品:";
            this.Label7.Enabled = true;
            this.Label7.Name = "Label7";
            this.Label8.Size  = new System.Drawing.Size(78, 12);
            this.Label8.Location  = new System.Drawing.Point(8, 44);
            this.Label8.Text = "命令制造物品:";
            this.Label8.Enabled = true;
            this.Label8.Name = "Label8";
            this.EditItemNumber.Size  = new System.Drawing.Size(73, 20);
            this.EditItemNumber.Location  = new System.Drawing.Point(88, 16);
            this.EditItemNumber.TabIndex = 0;
            this.EditItemNumber.ReadOnly = true;
            this.EditItemNumber.Enabled = true;
            this.EditItemNumber.Name = "EditItemNumber";
            this.EditItemNumberEx.Size  = new System.Drawing.Size(73, 20);
            this.EditItemNumberEx.Location  = new System.Drawing.Point(88, 40);
            this.EditItemNumberEx.TabIndex = 1;
            this.EditItemNumberEx.ReadOnly = true;
            this.EditItemNumberEx.Enabled = true;
            this.EditItemNumberEx.Name = "EditItemNumberEx";
            this.TabSheet2.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet2.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet2.SuspendLayout();
            this.TabSheet2.Text = "彩票数据";
            this.TabSheet2.ImageIndex = 1;
            this.TabSheet2.Enabled = true;
            this.TabSheet2.Name = "TabSheet2";
            this.GroupBox2.Size  = new System.Drawing.Size(153, 77);
            this.GroupBox2.Location  = new System.Drawing.Point(8, 4);
            this.GroupBox2.SuspendLayout();
            this.GroupBox2.Text = "中奖数量";
            this.GroupBox2.TabIndex = 0;
            this.GroupBox2.Enabled = true;
            this.GroupBox2.Name = "GroupBox2";
            this.Label5.Size  = new System.Drawing.Size(54, 12);
            this.Label5.Location  = new System.Drawing.Point(8, 20);
            this.Label5.Text = "中奖总数:";
            this.Label5.Enabled = true;
            this.Label5.Name = "Label5";
            this.Label6.Size  = new System.Drawing.Size(54, 12);
            this.Label6.Location  = new System.Drawing.Point(8, 44);
            this.Label6.Text = "未中奖数:";
            this.Label6.Enabled = true;
            this.Label6.Name = "Label6";
            this.EditWinLotteryCount.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryCount.Location  = new System.Drawing.Point(88, 16);
            this.EditWinLotteryCount.TabIndex = 0;
            this.EditWinLotteryCount.ReadOnly = true;
            this.EditWinLotteryCount.Enabled = true;
            this.EditWinLotteryCount.Name = "EditWinLotteryCount";
            this.EditNoWinLotteryCount.Size  = new System.Drawing.Size(57, 20);
            this.EditNoWinLotteryCount.Location  = new System.Drawing.Point(88, 40);
            this.EditNoWinLotteryCount.TabIndex = 1;
            this.EditNoWinLotteryCount.ReadOnly = true;
            this.EditNoWinLotteryCount.Enabled = true;
            this.EditNoWinLotteryCount.Name = "EditNoWinLotteryCount";
            this.GroupBox3.Size  = new System.Drawing.Size(129, 165);
            this.GroupBox3.Location  = new System.Drawing.Point(168, 4);
            this.GroupBox3.SuspendLayout();
            this.GroupBox3.Text = "中奖比例";
            this.GroupBox3.TabIndex = 1;
            this.GroupBox3.Enabled = true;
            this.GroupBox3.Name = "GroupBox3";
            this.Label9.Size  = new System.Drawing.Size(42, 12);
            this.Label9.Location  = new System.Drawing.Point(8, 20);
            this.Label9.Text = "一等奖:";
            this.Label9.Enabled = true;
            this.Label9.Name = "Label9";
            this.Label10.Size  = new System.Drawing.Size(42, 12);
            this.Label10.Location  = new System.Drawing.Point(8, 44);
            this.Label10.Text = "二等奖:";
            this.Label10.Enabled = true;
            this.Label10.Name = "Label10";
            this.Label11.Size  = new System.Drawing.Size(42, 12);
            this.Label11.Location  = new System.Drawing.Point(8, 68);
            this.Label11.Text = "三等奖:";
            this.Label11.Enabled = true;
            this.Label11.Name = "Label11";
            this.Label12.Size  = new System.Drawing.Size(42, 12);
            this.Label12.Location  = new System.Drawing.Point(8, 92);
            this.Label12.Text = "四等奖:";
            this.Label12.Enabled = true;
            this.Label12.Name = "Label12";
            this.Label13.Size  = new System.Drawing.Size(42, 12);
            this.Label13.Location  = new System.Drawing.Point(8, 116);
            this.Label13.Text = "五等奖:";
            this.Label13.Enabled = true;
            this.Label13.Name = "Label13";
            this.Label14.Size  = new System.Drawing.Size(42, 12);
            this.Label14.Location  = new System.Drawing.Point(8, 140);
            this.Label14.Text = "六等奖:";
            this.Label14.Enabled = true;
            this.Label14.Name = "Label14";
            this.EditWinLotteryLevel1.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel1.Location  = new System.Drawing.Point(56, 16);
            this.EditWinLotteryLevel1.TabIndex = 0;
            this.EditWinLotteryLevel1.ReadOnly = true;
            this.EditWinLotteryLevel1.Enabled = true;
            this.EditWinLotteryLevel1.Name = "EditWinLotteryLevel1";
            this.EditWinLotteryLevel2.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel2.Location  = new System.Drawing.Point(56, 40);
            this.EditWinLotteryLevel2.TabIndex = 1;
            this.EditWinLotteryLevel2.ReadOnly = true;
            this.EditWinLotteryLevel2.Enabled = true;
            this.EditWinLotteryLevel2.Name = "EditWinLotteryLevel2";
            this.EditWinLotteryLevel3.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel3.Location  = new System.Drawing.Point(56, 64);
            this.EditWinLotteryLevel3.TabIndex = 2;
            this.EditWinLotteryLevel3.ReadOnly = true;
            this.EditWinLotteryLevel3.Enabled = true;
            this.EditWinLotteryLevel3.Name = "EditWinLotteryLevel3";
            this.EditWinLotteryLevel4.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel4.Location  = new System.Drawing.Point(56, 88);
            this.EditWinLotteryLevel4.TabIndex = 3;
            this.EditWinLotteryLevel4.ReadOnly = true;
            this.EditWinLotteryLevel4.Enabled = true;
            this.EditWinLotteryLevel4.Name = "EditWinLotteryLevel4";
            this.EditWinLotteryLevel5.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel5.Location  = new System.Drawing.Point(56, 112);
            this.EditWinLotteryLevel5.TabIndex = 4;
            this.EditWinLotteryLevel5.ReadOnly = true;
            this.EditWinLotteryLevel5.Enabled = true;
            this.EditWinLotteryLevel5.Name = "EditWinLotteryLevel5";
            this.EditWinLotteryLevel6.Size  = new System.Drawing.Size(57, 20);
            this.EditWinLotteryLevel6.Location  = new System.Drawing.Point(56, 136);
            this.EditWinLotteryLevel6.TabIndex = 5;
            this.EditWinLotteryLevel6.ReadOnly = true;
            this.EditWinLotteryLevel6.Enabled = true;
            this.EditWinLotteryLevel6.Name = "EditWinLotteryLevel6";
            this.TabSheet3.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet3.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet3.SuspendLayout();
            this.TabSheet3.Text = "全局变量";
            this.TabSheet3.ImageIndex = 2;
            this.TabSheet3.Enabled = true;
            this.TabSheet3.Name = "TabSheet3";
            this.GroupBox5.Size  = new System.Drawing.Size(425, 165);
            this.GroupBox5.Location  = new System.Drawing.Point(8, 4);
            this.GroupBox5.SuspendLayout();
            this.GroupBox5.Text = "全局变量状态";
            this.GroupBox5.TabIndex = 0;
            this.GroupBox5.Enabled = true;
            this.GroupBox5.Name = "GroupBox5";
            this.Label15.Size  = new System.Drawing.Size(42, 12);
            this.Label15.Location  = new System.Drawing.Point(8, 20);
            this.Label15.Text = "变量一:";
            this.Label15.Enabled = true;
            this.Label15.Name = "Label15";
            this.Label16.Size  = new System.Drawing.Size(42, 12);
            this.Label16.Location  = new System.Drawing.Point(8, 44);
            this.Label16.Text = "变量二:";
            this.Label16.Enabled = true;
            this.Label16.Name = "Label16";
            this.Label17.Size  = new System.Drawing.Size(42, 12);
            this.Label17.Location  = new System.Drawing.Point(8, 68);
            this.Label17.Text = "变量三:";
            this.Label17.Enabled = true;
            this.Label17.Name = "Label17";
            this.Label18.Size  = new System.Drawing.Size(42, 12);
            this.Label18.Location  = new System.Drawing.Point(8, 92);
            this.Label18.Text = "变量四:";
            this.Label18.Enabled = true;
            this.Label18.Name = "Label18";
            this.Label19.Size  = new System.Drawing.Size(42, 12);
            this.Label19.Location  = new System.Drawing.Point(8, 116);
            this.Label19.Text = "变量五:";
            this.Label19.Enabled = true;
            this.Label19.Name = "Label19";
            this.Label20.Size  = new System.Drawing.Size(42, 12);
            this.Label20.Location  = new System.Drawing.Point(8, 140);
            this.Label20.Text = "变量六:";
            this.Label20.Enabled = true;
            this.Label20.Name = "Label20";
            this.Label21.Size  = new System.Drawing.Size(42, 12);
            this.Label21.Location  = new System.Drawing.Point(120, 92);
            this.Label21.Text = "变量十:";
            this.Label21.Enabled = true;
            this.Label21.Name = "Label21";
            this.Label22.Size  = new System.Drawing.Size(42, 12);
            this.Label22.Location  = new System.Drawing.Point(120, 20);
            this.Label22.Text = "变量七:";
            this.Label22.Enabled = true;
            this.Label22.Name = "Label22";
            this.Label23.Size  = new System.Drawing.Size(42, 12);
            this.Label23.Location  = new System.Drawing.Point(120, 44);
            this.Label23.Text = "变量八:";
            this.Label23.Enabled = true;
            this.Label23.Name = "Label23";
            this.Label24.Size  = new System.Drawing.Size(42, 12);
            this.Label24.Location  = new System.Drawing.Point(120, 68);
            this.Label24.Text = "变量九:";
            this.Label24.Enabled = true;
            this.Label24.Name = "Label24";
            this.EditGlobalVal1.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal1.Location  = new System.Drawing.Point(56, 16);
            this.EditGlobalVal1.TabIndex = 0;
            this.EditGlobalVal1.ReadOnly = true;
            this.EditGlobalVal1.Enabled = true;
            this.EditGlobalVal1.Name = "EditGlobalVal1";
            this.EditGlobalVal2.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal2.Location  = new System.Drawing.Point(56, 40);
            this.EditGlobalVal2.TabIndex = 1;
            this.EditGlobalVal2.ReadOnly = true;
            this.EditGlobalVal2.Enabled = true;
            this.EditGlobalVal2.Name = "EditGlobalVal2";
            this.EditGlobalVal3.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal3.Location  = new System.Drawing.Point(56, 64);
            this.EditGlobalVal3.TabIndex = 2;
            this.EditGlobalVal3.ReadOnly = true;
            this.EditGlobalVal3.Enabled = true;
            this.EditGlobalVal3.Name = "EditGlobalVal3";
            this.EditGlobalVal4.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal4.Location  = new System.Drawing.Point(56, 88);
            this.EditGlobalVal4.TabIndex = 3;
            this.EditGlobalVal4.ReadOnly = true;
            this.EditGlobalVal4.Enabled = true;
            this.EditGlobalVal4.Name = "EditGlobalVal4";
            this.EditGlobalVal5.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal5.Location  = new System.Drawing.Point(56, 112);
            this.EditGlobalVal5.TabIndex = 4;
            this.EditGlobalVal5.ReadOnly = true;
            this.EditGlobalVal5.Enabled = true;
            this.EditGlobalVal5.Name = "EditGlobalVal5";
            this.EditGlobalVal6.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal6.Location  = new System.Drawing.Point(56, 136);
            this.EditGlobalVal6.TabIndex = 5;
            this.EditGlobalVal6.ReadOnly = true;
            this.EditGlobalVal6.Enabled = true;
            this.EditGlobalVal6.Name = "EditGlobalVal6";
            this.EditGlobalVal7.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal7.Location  = new System.Drawing.Point(168, 16);
            this.EditGlobalVal7.TabIndex = 6;
            this.EditGlobalVal7.ReadOnly = true;
            this.EditGlobalVal7.Enabled = true;
            this.EditGlobalVal7.Name = "EditGlobalVal7";
            this.EditGlobalVal8.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal8.Location  = new System.Drawing.Point(168, 40);
            this.EditGlobalVal8.TabIndex = 7;
            this.EditGlobalVal8.ReadOnly = true;
            this.EditGlobalVal8.Enabled = true;
            this.EditGlobalVal8.Name = "EditGlobalVal8";
            this.EditGlobalVal9.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal9.Location  = new System.Drawing.Point(168, 64);
            this.EditGlobalVal9.TabIndex = 8;
            this.EditGlobalVal9.ReadOnly = true;
            this.EditGlobalVal9.Enabled = true;
            this.EditGlobalVal9.Name = "EditGlobalVal9";
            this.EditGlobalVal10.Size  = new System.Drawing.Size(57, 20);
            this.EditGlobalVal10.Location  = new System.Drawing.Point(168, 88);
            this.EditGlobalVal10.TabIndex = 9;
            this.EditGlobalVal10.ReadOnly = true;
            this.EditGlobalVal10.Enabled = true;
            this.EditGlobalVal10.Name = "EditGlobalVal10";
            this.TabSheet5.Size  = new System.Drawing.Size(0, 0);
            this.TabSheet5.Location  = new System.Drawing.Point(0, 0);
            this.TabSheet5.SuspendLayout();
            this.TabSheet5.Text = "工作线程";
            this.TabSheet5.ImageIndex = 4;
            this.TabSheet5.Enabled = true;
            this.TabSheet5.Name = "TabSheet5";
            this.GroupBox7.Size  = new System.Drawing.Size(425, 165);
            this.GroupBox7.Location  = new System.Drawing.Point(8, 4);
            this.GroupBox7.SuspendLayout();
            this.GroupBox7.Text = "线程状态";
            this.GroupBox7.TabIndex = 0;
            this.GroupBox7.Enabled = true;
            this.GroupBox7.Name = "GroupBox7";
            ((System.ComponentModel.ISupportInitialize)(this.GridThread)).BeginInit();
            this.GridThread.Size  = new System.Drawing.Size(409, 137);
            this.GridThread.Location  = new System.Drawing.Point(8, 16);
            this.GridThread.Name = "GridThread";
            this.GridThread.Enabled = true;
            //this.GridThread.PreferredColumnWidth = (int){35, 50, 51, 90, 64};
            this.GridThread.TabIndex = 0;
            //this.Timer.Tick += new System.EventHandler(this.TimerTimer);
            this.Timer.Enabled = false;
            this.GroupBox6.Controls.Add(Label25);
            this.GroupBox6.Controls.Add(Label26);
            this.GroupBox6.Controls.Add(EditAllocMemCount);
            this.GroupBox6.Controls.Add(EditAllocMemSize);
            this.GroupBox6.ResumeLayout(false);
            this.TabSheet4.Controls.Add(GroupBox6);
            this.TabSheet4.ResumeLayout(false);
            this.GroupBox1.Controls.Add(Label1);
            this.GroupBox1.Controls.Add(Label2);
            this.GroupBox1.Controls.Add(Label3);
            this.GroupBox1.Controls.Add(Label4);
            this.GroupBox1.Controls.Add(EditLoadHumanDBCount);
            this.GroupBox1.Controls.Add(EditLoadHumanDBErrorCoun);
            this.GroupBox1.Controls.Add(EditSaveHumanDBCount);
            this.GroupBox1.Controls.Add(EditHumanDBQueryID);
            this.GroupBox1.ResumeLayout(false);
            this.GroupBox4.Controls.Add(Label7);
            this.GroupBox4.Controls.Add(Label8);
            this.GroupBox4.Controls.Add(EditItemNumber);
            this.GroupBox4.Controls.Add(EditItemNumberEx);
            this.GroupBox4.ResumeLayout(false);
            this.TabSheet1.Controls.Add(GroupBox1);
            this.TabSheet1.Controls.Add(GroupBox4);
            this.TabSheet1.ResumeLayout(false);
            this.GroupBox2.Controls.Add(Label5);
            this.GroupBox2.Controls.Add(Label6);
            this.GroupBox2.Controls.Add(EditWinLotteryCount);
            this.GroupBox2.Controls.Add(EditNoWinLotteryCount);
            this.GroupBox2.ResumeLayout(false);
            this.GroupBox3.Controls.Add(Label9);
            this.GroupBox3.Controls.Add(Label10);
            this.GroupBox3.Controls.Add(Label11);
            this.GroupBox3.Controls.Add(Label12);
            this.GroupBox3.Controls.Add(Label13);
            this.GroupBox3.Controls.Add(Label14);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel1);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel2);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel3);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel4);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel5);
            this.GroupBox3.Controls.Add(EditWinLotteryLevel6);
            this.GroupBox3.ResumeLayout(false);
            this.TabSheet2.Controls.Add(GroupBox2);
            this.TabSheet2.Controls.Add(GroupBox3);
            this.TabSheet2.ResumeLayout(false);
            this.GroupBox5.Controls.Add(Label15);
            this.GroupBox5.Controls.Add(Label16);
            this.GroupBox5.Controls.Add(Label17);
            this.GroupBox5.Controls.Add(Label18);
            this.GroupBox5.Controls.Add(Label19);
            this.GroupBox5.Controls.Add(Label20);
            this.GroupBox5.Controls.Add(Label21);
            this.GroupBox5.Controls.Add(Label22);
            this.GroupBox5.Controls.Add(Label23);
            this.GroupBox5.Controls.Add(Label24);
            this.GroupBox5.Controls.Add(EditGlobalVal1);
            this.GroupBox5.Controls.Add(EditGlobalVal2);
            this.GroupBox5.Controls.Add(EditGlobalVal3);
            this.GroupBox5.Controls.Add(EditGlobalVal4);
            this.GroupBox5.Controls.Add(EditGlobalVal5);
            this.GroupBox5.Controls.Add(EditGlobalVal6);
            this.GroupBox5.Controls.Add(EditGlobalVal7);
            this.GroupBox5.Controls.Add(EditGlobalVal8);
            this.GroupBox5.Controls.Add(EditGlobalVal9);
            this.GroupBox5.Controls.Add(EditGlobalVal10);
            this.GroupBox5.ResumeLayout(false);
            this.TabSheet3.Controls.Add(GroupBox5);
            this.TabSheet3.ResumeLayout(false);
            this.GroupBox7.Controls.Add(GridThread);
            ((System.ComponentModel.ISupportInitialize)(this.GridThread)).EndInit();
            this.GroupBox7.ResumeLayout(false);
            this.TabSheet5.Controls.Add(GroupBox7);
            this.TabSheet5.ResumeLayout(false);
            this.PageControl1.Controls.Add(TabSheet4);
            this.PageControl1.Controls.Add(TabSheet1);
            this.PageControl1.Controls.Add(TabSheet2);
            this.PageControl1.Controls.Add(TabSheet3);
            this.PageControl1.Controls.Add(TabSheet5);
            this.PageControl1.ResumeLayout(false);
            this.Controls.Add(PageControl1);
            this.ResumeLayout(false);
        }
#endregion

    }
}
